create type user_role as enum ('RESIDENT', 'COMMUNITY_ORGANIZER');
create type notification_type as enum ('NEW_INITIATIVE', 'NEW_COMMENT_ON_POST', 'NEW_LIKE_ON_POST', 'NEW_MESSAGE');
create type initiative_category as enum ('TOOL_SHARING', 'FOOD_SWAP', 'COMMUNITY_GARDENING', 'RECYCLING_DRIVE', 'RIDE_SHARING');
create type neighborhood as enum ('CENTRUM', 'VASTRA_HAMNEN', 'LIMHAMN', 'ROSENGARD', 'HYLLIE', 'MOLLEVANGEN', 'DAVIDSHALL', 'AUGUSTENBORG', 'KULLADAL', 'LORENSBORG', 'SOFIELUND', 'SORGENFRI', 'OXIE', 'RORSJOSTADEN', 'KIRSEBERG', 'BUNKEFLOSTRAND');
create type eco_action_category as enum ('TRANSPORT', 'WASTE', 'FOOD');

CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    location      neighborhood                            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name user_role                               NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    text       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (comment_id)
);

CREATE TABLE LIKES
(
    like_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id  BIGINT                                  NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    liked_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (like_id)
);

CREATE TABLE eco_action_types
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action            VARCHAR(255)                            NOT NULL,
    carbon_savings_kg DECIMAL                                 NOT NULL,
    category          eco_action_category                     NOT NULL,
    CONSTRAINT pk_eco_action_types PRIMARY KEY (id)
);

CREATE TABLE eco_actions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    eco_action_type_id BIGINT                                  NOT NULL,
    action_date        date                                    NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_eco_actions PRIMARY KEY (id)
);

CREATE TABLE initiative_members
(
    joined_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiative_id BIGINT                      NOT NULL,
    user_id       BIGINT                      NOT NULL,
    CONSTRAINT pk_initiative_members PRIMARY KEY (initiative_id, user_id)
);

CREATE TABLE initiatives
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    location    VARCHAR(255)                            NOT NULL,
    category    initiative_category                     NOT NULL,
    is_public   BOOLEAN                                 NOT NULL,
    creator_id  BIGINT                                  NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_initiatives PRIMARY KEY (id)
);

CREATE TABLE post_images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    image_url  VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_post_images PRIMARY KEY (id)
);

CREATE TABLE posts
(
    post_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiative_id BIGINT                                  NOT NULL,
    author_id     BIGINT                                  NOT NULL,
    text          VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (post_id)
);

CREATE TABLE messages
(
    message_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id   BIGINT                                  NOT NULL,
    receiver_id BIGINT                                  NOT NULL,
    text        VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT  pk_messages PRIMARY KEY (message_id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_role_name UNIQUE (role_name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (post_id);

ALTER TABLE LIKES
    ADD CONSTRAINT FK_LIKES_ON_POST FOREIGN KEY (post_id) REFERENCES posts (post_id);

ALTER TABLE LIKES
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE eco_actions
    ADD CONSTRAINT FK_ECO_ACTIONS_ON_ECO_ACTION_TYPE FOREIGN KEY (eco_action_type_id) REFERENCES eco_action_types (id);

ALTER TABLE eco_actions
    ADD CONSTRAINT FK_ECO_ACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE initiatives
    ADD CONSTRAINT FK_INITIATIVES_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (user_id);

ALTER TABLE initiative_members
    ADD CONSTRAINT FK_INITIATIVE_MEMBERS_ON_INITIATIVE FOREIGN KEY (initiative_id) REFERENCES initiatives (id);

ALTER TABLE initiative_members
    ADD CONSTRAINT FK_INITIATIVE_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_INITIATIVE FOREIGN KEY (initiative_id) REFERENCES initiatives (id);

ALTER TABLE post_images
    ADD CONSTRAINT FK_POST_IMAGES_ON_POST FOREIGN KEY (post_id) REFERENCES posts (post_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (user_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES posts (user_id);

INSERT INTO roles (role_name)
VALUES ('RESIDENT');
INSERT INTO roles (role_name)
VALUES ('COMMUNITY_ORGANIZER');

INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Biked to work', 2.30, 'TRANSPORT');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Carpooled to event', 3.10, 'TRANSPORT');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Used public transport', 1.50, 'TRANSPORT');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Drove electric vehicle', 2.00, 'TRANSPORT');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Used reusable bags for shopping', 0.10, 'WASTE');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Recycled household waste', 0.50, 'WASTE');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Composted food scraps', 0.70, 'WASTE');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Ate vegetarian meal', 1.00, 'FOOD');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Participated in community garden', 1.20, 'FOOD');
INSERT INTO eco_action_types (action, carbon_savings_kg, category)
VALUES ('Chose local/seasonal produce', 0.80, 'FOOD');