CREATE TABLE messages
(
    message_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id   BIGINT                                  NOT NULL,
    receiver_id BIGINT                                  NOT NULL,
    text        VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT  pk_messages PRIMARY KEY (message_id)
);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (user_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES users (user_id);